# backend/app/api/chat.py
from fastapi import APIRouter, Depends, HTTPException, Header
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
import json
import uuid
import logging
from typing import Optional

from app.database import get_db, AsyncSessionLocal
from app.config import get_settings
from app.models.db_models import SessionModel, MessageModel, ArtifactModel
from app.models.schemas import ChatRequest
from app.rag.retriever import TranscriptRetriever
from app.rag.embeddings import get_embedding
from app.providers import get_llm_provider
from app.skills.ship30_writer import build_ship30_prompt
from app.skills.artifact_generator import extract_artifacts_from_text

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/chat", tags=["Chat"])

REFUSAL_MESSAGE = "I do not have sufficient information in Lenny's podcast archive to answer this."

GROUNDED_SYSTEM_PROMPT = """You are "The Lenny Growth Assistant", an elite product and growth executive advisor.
Your mission is to synthesize insights from Lenny's Podcast into clear, structured, context-aware answers.

### STRICT OPERATIONAL RULES:
1. Context-Aware Synthesis: Directly answer the user's specific question in your own professional words. DO NOT copy or output raw transcript text, verbatim dialogues, or speaker interview transcripts.
2. Structured & Clear Formatting:
   - Begin with a direct 2-3 sentence executive answer addressing the user's question directly.
   - Use clear markdown sections with bullet points featuring **bold anchor keywords** to explain key mechanisms, contrasting concepts, or frameworks.
   - Conclude with an actionable takeaway for product leaders.
3. Natural Attribution:
   - Attribute insights naturally at the end of key points (e.g. *Source: Brian Chesky on "Brian Chesky's New Playbook"*).
   - DO NOT begin your response with raw bracketed headers.
4. Strict Grounding:
   - Base all reasoning on the provided podcast insights. If the provided excerpts do not contain enough information to answer the question, state:
     "I do not have sufficient information in Lenny's podcast archive to answer this."
5. Artifacts:
   - When asked for a tool, calculator, or interactive model, wrap in:
     <artifact type="html" title="...">...</artifact>
   - When asked for a comprehensive document or memo, wrap in:
     <artifact type="markdown" title="...">...</artifact>
"""

@router.post("")
async def chat_stream(
    req: ChatRequest,
    x_llm_provider: Optional[str] = Header(None, alias="X-LLM-Provider"),
    db: AsyncSession = Depends(get_db)
):
    """
    Stream conversational responses, source citations, and dynamic artifacts 
    over Server-Sent Events (SSE).
    """
    settings = get_settings()

    # 1. Validate / retrieve session
    try:
        session_uuid = uuid.UUID(req.session_id)
    except Exception:
        session_uuid = uuid.uuid5(uuid.NAMESPACE_DNS, str(req.session_id))

    if db is not None:
        try:
            result = await db.execute(select(SessionModel).where(SessionModel.id == session_uuid))
            session_obj = result.scalar_one_or_none()
            if not session_obj:
                # Create session automatically if ID was generated by frontend
                session_obj = SessionModel(id=session_uuid, title=req.message[:50] + "...")
                db.add(session_obj)
                await db.commit()
        except Exception as e:
            logger.warning(f"Could not persist session to DB: {e}")

    # 2. Select Provider (request body > header > default)
    selected_provider = req.provider or x_llm_provider or settings.DEFAULT_PROVIDER
    llm = get_llm_provider(selected_provider)

    # Detect /ship or /ship30 skill command in prompt or mode
    is_ship = (req.mode in ["ship", "ship30"])
    clean_message = req.message.strip()
    if clean_message.lower().startswith("/ship30"):
        is_ship = True
        remainder = clean_message[7:].strip()
        if remainder:
            clean_message = remainder
    elif clean_message.lower().startswith("/ship"):
        is_ship = True
        remainder = clean_message[5:].strip()
        if remainder:
            clean_message = remainder

    lower_msg = clean_message.lower()

    # Dynamic Scenario-Aware Status Notification
    if is_ship or "ship30" in lower_msg or "ship " in lower_msg:
        status_msg = "Drafting Ship 30 for 30 essay in Artifacts..."
    elif any(k in lower_msg for k in ["md file", "markdown file", "artifact", "save as file", "make a file", "create a file", "export"]):
        status_msg = "Compiling document artifact..."
    elif any(k in lower_msg for k in ["calculator", "spreadsheet", "interactive", "tool", "simulator"]):
        status_msg = "Building interactive tool artifact..."
    elif any(k in lower_msg for k in ["summarize", "explain", "compare", "difference", "vs", "versus"]):
        status_msg = "Synthesizing podcast insights..."
    else:
        status_msg = "Searching Lenny's podcast archive..."

    # Retrieve past session history for multi-turn conversational context
    from app.api.sessions import IN_MEMORY_SESSIONS
    past_messages = []
    sess = IN_MEMORY_SESSIONS.get(str(session_uuid))
    if sess and "messages" in sess:
        past_messages = sess["messages"]
    elif db is not None:
        try:
            res = await db.execute(
                select(MessageModel)
                .where(MessageModel.session_id == session_uuid)
                .order_by(MessageModel.created_at)
            )
            all_msgs = res.scalars().all()
            past_messages = [{"role": m.role, "content": m.content} for m in all_msgs]
        except Exception as e:
            logger.warning(f"Could not load past DB messages: {e}")

    # Check if user is asking to create an artifact or file from previous discussion
    is_artifact_request = any(
        k in lower_msg for k in ["md file", "markdown file", "artifact", "save as file", "make a file", "create a file", "export to md", "export as file"]
    )
    last_assistant_msg = None
    if past_messages:
        for m in reversed(past_messages):
            if m.get("role") == "assistant" and len(m.get("content", "").strip()) > 30:
                last_assistant_msg = m.get("content", "").strip()
                break

    # 3. Retrieve relevant chunks from pgvector
    retriever = TranscriptRetriever(db, get_embedding)
    chunks = await retriever.retrieve_relevant_chunks(
        query=clean_message,
        top_k=settings.TOP_K_CHUNKS,
        similarity_threshold=settings.SIMILARITY_THRESHOLD
    )

    # 4. SSE Stream Generator
    async def event_generator():
        # Step A: Dynamic Status notification
        yield f"data: {json.dumps({'type': 'status', 'content': status_msg})}\n\n"
        
        # Step B: Yield sources
        yield f"data: {json.dumps({'type': 'sources', 'data': chunks})}\n\n"

        full_assistant_response = ""

        # Step C: Check if this is an artifact request on prior conversation
        if is_artifact_request and last_assistant_msg:
            system_prompt = (
                "You are an elite product editor and technical writer.\n"
                "The user wants you to format the previously discussed content into a clean, standalone Markdown artifact.\n"
                "INSTRUCTIONS:\n"
                "1. Output a brief 1-sentence confirmation in the chat (e.g. 'I have created the Markdown artifact for you.').\n"
                "2. Wrap the complete document inside an artifact container:\n"
                "<artifact type=\"markdown\" title=\"Operational Essay & Framework\">\n"
                "# Operational Essay & Framework\n\n"
                "[Full formatted content with headings, bullet points, and actionable takeaways]\n"
                "</artifact>"
            )
            messages = [
                {"role": "user", "content": f"Please convert this content into a dedicated Markdown artifact file:\n\n{last_assistant_msg}"}
            ]
        elif not chunks:
            # Grounding refusal circuit-breaker for ungrounded queries
            logger.info(f"Refusal triggered: query '{clean_message[:40]}' had 0 chunks above {settings.SIMILARITY_THRESHOLD}")
            yield f"data: {json.dumps({'type': 'token', 'content': REFUSAL_MESSAGE})}\n\n"
            full_assistant_response = REFUSAL_MESSAGE
            yield "data: [DONE]\n\n"
            await _persist_conversation(session_uuid, req.message, full_assistant_response, chunks)
            return
        elif is_ship:
            system_prompt = "You are an elite ghostwriter following the Ship 30 for 30 framework."
            user_prompt = build_ship30_prompt(clean_message, chunks)
            messages = [{"role": "user", "content": user_prompt}]
        else:
            system_prompt = GROUNDED_SYSTEM_PROMPT
            clean_context = []
            for c in chunks:
                clean_context.append(
                    f"Episode: {c['episode']} (Guest: {c['guest']}) [Timestamp: {c['timestamp']}]:\n{c['text']}"
                )
            context_block = "\n\n---\n\n".join(clean_context)

            # Include recent turns if available for conversational flow
            conv_history = ""
            if past_messages:
                recent = past_messages[-4:]
                turns = [f"{m['role'].capitalize()}: {m['content'][:250]}" for m in recent]
                conv_history = "RECENT CONVERSATION HISTORY:\n" + "\n".join(turns) + "\n\n"

            messages = [
                {
                    "role": "user", 
                    "content": (
                        f"{conv_history}"
                        f"Please provide a clear, context-aware answer to the question using the podcast insights below.\n\n"
                        f"USER QUESTION:\n{clean_message}\n\n"
                        f"PODCAST INSIGHTS:\n{context_block}\n\n"
                        f"INSTRUCTIONS:\n"
                        f"- Synthesize the answer in your own clear words to directly answer: \"{clean_message}\".\n"
                        f"- DO NOT copy verbatim sentences or interview dialogue.\n"
                        f"- Use structured markdown with bullet points and **bold anchor keywords**."
                    )
                }
            ]

        # Step E: Stream tokens from selected LLM
        try:
            async for token in llm.generate_response(messages, system_prompt):
                full_assistant_response += token
                yield f"data: {json.dumps({'type': 'token', 'content': token})}\n\n"
        except Exception as e:
            logger.error(f"Error during LLM stream generation: {e}")
            err_msg = f"\n[Generation error: {str(e)}]"
            full_assistant_response += err_msg
            yield f"data: {json.dumps({'type': 'token', 'content': err_msg})}\n\n"

        # Step F: Extract and notify client of any generated artifacts
        extracted_artifacts = extract_artifacts_from_text(full_assistant_response)
        if is_ship and not extracted_artifacts and len(full_assistant_response) > 50:
            # Guarantee artifact generation for /ship requests even if LLM missed enclosing tags
            title = f"Ship 30 Essay: {clean_message[:45]}"
            extracted_artifacts = [{
                "artifact_type": "markdown",
                "title": title,
                "content": full_assistant_response.strip()
            }]

        if extracted_artifacts:
            for art in extracted_artifacts:
                yield f"data: {json.dumps({'type': 'artifact', 'data': art})}\n\n"

        yield "data: [DONE]\n\n"

        # Step G: Persist messages and artifacts asynchronously
        from app.skills.artifact_generator import clean_response_text
        cleaned_saved_response = clean_response_text(full_assistant_response) or full_assistant_response
        await _persist_conversation(session_uuid, req.message, cleaned_saved_response, chunks, extracted_artifacts)

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"
        }
    )

async def _persist_conversation(
    session_id: uuid.UUID,
    user_msg: str,
    assistant_msg: str,
    sources: list,
    artifacts: list = None
):
    """Save messages and artifacts in memory and fresh database session."""
    from app.api.sessions import IN_MEMORY_SESSIONS
    from datetime import datetime
    now = datetime.utcnow()
    asst_id = str(uuid.uuid4())

    formatted_artifacts = []
    if artifacts:
        for art in artifacts:
            formatted_artifacts.append({
                "id": str(art.get("id") or uuid.uuid4()),
                "message_id": asst_id,
                "artifact_type": art.get("artifact_type", "markdown"),
                "title": art.get("title", "Artifact"),
                "content": art.get("content", ""),
                "created_at": now.isoformat()
            })

    # Always persist in in-memory session if available
    sess = IN_MEMORY_SESSIONS.get(str(session_id))
    if sess:
        user_m = {
            "id": str(uuid.uuid4()),
            "session_id": str(session_id),
            "role": "user",
            "content": user_msg,
            "created_at": now.isoformat(),
            "sources": []
        }
        asst_m = {
            "id": asst_id,
            "session_id": str(session_id),
            "role": "assistant",
            "content": assistant_msg,
            "created_at": now.isoformat(),
            "sources": sources,
            "artifacts": formatted_artifacts
        }
        sess.setdefault("messages", []).extend([user_m, asst_m])
        sess["updated_at"] = now

    if AsyncSessionLocal is None:
        return

    try:
        async with AsyncSessionLocal() as session:
            user_record = MessageModel(
                session_id=session_id,
                role="user",
                content=user_msg,
                sources=[]
            )
            session.add(user_record)

            assistant_record = MessageModel(
                session_id=session_id,
                role="assistant",
                content=assistant_msg,
                sources=sources
            )
            session.add(assistant_record)
            await session.flush()  # obtain assistant_record.id

            if artifacts:
                for art in artifacts:
                    artifact_record = ArtifactModel(
                        message_id=assistant_record.id,
                        artifact_type=art["artifact_type"],
                        title=art["title"],
                        content=art["content"]
                    )
                    session.add(artifact_record)

            await session.commit()
            logger.info(f"Persisted conversation turn for session: {session_id}")
    except Exception as e:
        logger.error(f"Error persisting conversation to database: {e}")
